const data = {
    products: [
        {
            _id: '1',
            name: 'Nike Slim Shirt',
            catagory: "Shirts",
            image: '/images/p1.jpg',
            price: 120,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10, 
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'T Shirt',
            catagory: "Shirts",
            image: '/images/p1.jpg',
            price: 80,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10, 
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'M T Shirt',
            catagory: "Shirts",
            image: '/images/p1.jpg',
            price: 170,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10, 
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'M T Shirt',
            catagory: "Shirts",
            image: '/images/p1.jpg',
            price: 130,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10, 
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'M T Shirt',
            catagory: "Shirts",
            image: '/images/p1.jpg',
            price: 210,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10, 
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'M T Shirt',
            catagory: "Shirts",
            image: '/images/p1.jpg',
            price: 20,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10, 
            description: 'high quality product',
        },
    ]
}
export default data;